site_name: Bocobot Tournament
site_url: https://sitename.example
site_author: Sergio González Rodríguez
site_description: Resources for the Bocobot Robotics Tournament
repo_url: https://github.com/Sergiooo0/Bocobot-Tournament-WebPage
repo_name: Bocobot Tournament WebPage


theme:
  name: material
  language: es

  features:
    - navigation.tabs
    - navigation.top  # Back to top button
    - toc.integrate  # Integrates TOC in left menu instead of right
    #- navigation.footer

  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro

    # Dark mode
    - scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

  icon:
    logo: material/robot-industrial
  
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Inicio: index.md
  - Tutorial de Montaje: tutorial-montaje.md

extra:
  generator: false  # Hides "Made with MkDocs"
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sergio-gonzalez-rodriguez4/
    - icon: fontawesome/brands/github
      link: https://github.com/Sergiooo0


markdown_extensions:
  - attr_list  # To add CSS classes
  - md_in_html  # To use HTML inside markdown
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - stylesheets/custom.css
