site_name: Bocobot Tournament
site_url: https://sergiooo0.github.io/Bocobot-Tournament-WebPage/
site_author: Sergio González Rodríguez
site_description: "Torneo de Robótica Bocobot — ESEI Ourense, 27 de abril. ¡Monta, programa y compite con tu propio robot!"
repo_url: https://github.com/Sergiooo0/Bocobot-Tournament-WebPage
repo_name: Bocobot Tournament WebPage


theme:
  name: material
  language: es

  features:
    - navigation.tabs
    - navigation.top  # Back to top button
    - toc.integrate  # Integrates TOC in left menu instead of right
    - navigation.footer

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Cambiar a modo claro

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Cambiar a preferencia de sistema

  icon:
    logo: material/robot-industrial
  
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Inicio: index.md
  - Normas del Torneo: normas.md
  - Guía del Robot: guia-robot.md
  - ¡Inscríbete!: "https://docs.google.com/forms/d/e/1FAIpQLScpvvbQE-pS9H050xOW6uJyefBrO_nOn3Itc3BrAmD3Ni02DA/viewform"  

extra:
  generator: false  # Hides "Made with MkDocs"
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sergio-gonzalez-rodriguez4/
    - icon: fontawesome/brands/github
      link: https://github.com/Sergiooo0


markdown_extensions:
  - attr_list  # To add CSS classes
  - md_in_html  # To use HTML inside markdown
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - stylesheets/custom.css
